import React, { useEffect, useState } from 'react';
import { getDashboard } from '../services/api';
import type { DashboardResponse } from '../types';
import ChartRenderer from './ChartRenderer';
import { AlertTriangle, Info, CheckCircle, Loader2 } from 'lucide-react';

interface DashboardProps {
  role: string;
}

const Dashboard: React.FC<DashboardProps> = ({ role }) => {
  const [data, setData] = useState<DashboardResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchDashboard = async () => {
      setLoading(true);
      setError(null);
      try {
        const result = await getDashboard(role);
        setData(result);
      } catch (err) {
        setError('Failed to load dashboard data');
        console.error(err);
      } finally {
        setLoading(false);
      }
    };

    fetchDashboard();
  }, [role]);

  if (loading) {
    return (
      <div className="flex items-center justify-center h-full">
        <Loader2 className="w-8 h-8 text-blue-600 animate-spin" />
      </div>
    );
  }

  if (error || !data) {
    return (
      <div className="p-8 text-center text-red-600">
        {error || 'Something went wrong'}
      </div>
    );
  }

  // Helper to resolve data source string (e.g., "metrics.scope_completion") to actual data
  const resolveDataSource = (path: string) => {
    const parts = path.split('.');
    let current: any = data;
    for (const part of parts) {
      if (current[part] === undefined) return null;
      current = current[part];
    }
    return current;
  };

  return (
    <div className="p-8">
      <header className="mb-8">
        <h1 className="text-3xl font-bold text-gray-900">{role} Dashboard</h1>
        <p className="text-gray-500 mt-2">Real-time agile delivery insights generated by AI</p>
      </header>

      {/* AI Summary */}
      <section className="bg-blue-50 border-l-4 border-blue-600 p-6 rounded-r-lg mb-8">
        <div className="flex items-start">
          <Info className="w-6 h-6 text-blue-600 mr-3 mt-0.5" />
          <div>
            <h2 className="text-lg font-semibold text-blue-900 mb-1">AI Insights Summary</h2>
            <p className="text-blue-800 leading-relaxed">{data.summary}</p>
          </div>
        </div>
      </section>

      {/* Alerts */}
      {data.alerts.length > 0 && (
        <section className="mb-8 flex flex-col gap-3">
          {data.alerts.map((alert, idx) => (
            <div key={idx} className={`p-4 rounded-lg flex items-center ${
              alert.severity === 'high' ? 'bg-red-50 border border-red-200 text-red-800' :
              alert.severity === 'medium' ? 'bg-amber-50 border border-amber-200 text-amber-800' :
              'bg-blue-50 border border-blue-200 text-blue-800'
            }`}>
              <AlertTriangle className="w-5 h-5 mr-3 flex-shrink-0" />
              <span className="font-medium mr-2 uppercase text-xs">{alert.severity}</span>
              {alert.message}
            </div>
          ))}
        </section>
      )}

      {/* Visualisations Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-8">
        {data.visualisations.map((viz, idx) => (
          <ChartRenderer
            key={idx}
            spec={viz}
            data={resolveDataSource(viz.data_source)}
          />
        ))}
      </div>

      {/* Drilldown Navigation Links */}
      <section className="border-t border-gray-200 pt-8 mt-12">
        <h3 className="text-xl font-bold text-gray-900 mb-4">Deep Dive Exploration</h3>
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <button className="p-4 bg-white border border-gray-200 rounded-lg hover:border-blue-600 hover:text-blue-600 transition-all font-medium text-left">
                View Epics
            </button>
            <button className="p-4 bg-white border border-gray-200 rounded-lg hover:border-blue-600 hover:text-blue-600 transition-all font-medium text-left">
                Track Stories
            </button>
            <button className="p-4 bg-white border border-gray-200 rounded-lg hover:border-blue-600 hover:text-blue-600 transition-all font-medium text-left">
                Commits History
            </button>
            <button className="p-4 bg-white border border-gray-200 rounded-lg hover:border-blue-600 hover:text-blue-600 transition-all font-medium text-left">
                CICD Pipeline
            </button>
        </div>
      </section>
    </div>
  );
};

export default Dashboard;
